export const SUPPORTED_CURRENCIES = [
  // {
  //   name: "Solana USDT",
  //   cid: "USDT_SOL",
  //   currency: "USDT_SOL",
  //   icon: "https://plisio.net/img/psys-icon/USDT_SOL.svg",
  //   rate_usd: "0.9999100080992710656",
  //   price_usd: "1.000090",
  //   precision: 6,
  //   output_precision: 9,
  //   fiat: "USD",
  //   fiat_rate: "0.999910",
  //   min_sum_in: "0.999910000",
  //   invoice_commission_percentage: "1",
  //   hidden: 0,
  //   maintenance: false,
  //   contractOf: "SOL",
  //   contractStandard: "SPL",
  //   allowMemo: false,
  // },
  {
    name: "Solana",
    cid: "SOL",
    currency: "SOL",
    icon: "https://plisio.net/img/psys-icon/SOL.svg",
    rate_usd: "0.0057097179399337672719",
    price_usd: "175.140000000",
    precision: 9,
    output_precision: 9,
    fiat: "USD",
    fiat_rate: "0.005709717",
    min_sum_in: "0.000057097",
    invoice_commission_percentage: "0.5",
    hidden: 0,
    maintenance: false,
    contractOf: null,
    contractStandard: "SPL",
    allowMemo: false,
  },
  // {
  //   name: "Solana USDC",
  //   cid: "USDC_SOL",
  //   currency: "USDC_SOL",
  //   icon: "https://plisio.net/img/psys-icon/USDC_SOL.svg",
  //   rate_usd: "1.0001000100010001",
  //   price_usd: "0.999900",
  //   precision: 6,
  //   output_precision: 9,
  //   fiat: "USD",
  //   fiat_rate: "1.000100",
  //   min_sum_in: 0,
  //   invoice_commission_percentage: "1",
  //   hidden: 0,
  //   maintenance: false,
  //   contractOf: "SOL",
  //   contractStandard: "SPL",
  //   allowMemo: false,
  // },
];
